# ===============================
# APPLICATION
# ===============================
spring.application.name=mindtech

# ===============================
# DATASOURCE - MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/mindtech
spring.datasource.username=root
spring.datasource.password=Lukinhas123

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# ===============================
# CONNECTION POOL (HikariCP)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# ===============================
# Secrets
# ===============================
api.security.token.secret=${JWT_SECRET:Zqw9TGKLqD0rGXc2t473tUOOaYpODjyl2meObmXchcI=}